In [1]:
import pandas as pd
df = pd.read_csv("dt.csv")
my_players_set = ('R Laird', 'J Sicily', 'S Murray', 'J Finlayson', 
                   'I Cumming', 'N Coffield', 'A Pearce', 'A Naughton', 
                  'J McCrae', 'T Mitchell', 'N Fyfe', 'S Coniglio', 'P Dangerfield', 
                  'D Martin', 'Z Merrett', 'T Kelly', 'E Phillips', 'K Mutch', 'M Gawn', 
                  'S Martin', 'B Crossley', 'D Cameron', 'T McLean', 'I Heeney', 'S Menegola', 
                   'D Smith', 'B Fritsch', 'J Waterman', 'L Keeffe', 'C Rayner')
my_players_df = df.loc[df['player'].isin(my_players_set)]
my_players_df

,player,position,start_price,current_price,own,games,be,round_1,round_2,round_3,round_4,round_5,round_6,round_7,round_8,round_9
2,P Dangerfield,Mid,849000.0,695000.0,20.6,8.0,111.0,NaN,118.0,102.0,97.0,109.0,70.0,109.0,106.0,105.0
10,R Laird,Def,707000.0,708000.0,70.2,9.0,129.0,124.0,141.0,120.0,115.0,89.0,114.0,100.0,83.0,102.0
28,S Martin,Ruc,703000.0,730000.0,20.1,9.0,118.0,94.0,68.0,177.0,101.0,99.0,92.0,130.0,113.0,96.0
57,L Keeffe,"Def,Fwd",170000.0,253000.0,22.8,3.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,76.0,49.0,41.0
86,N Fyfe,Mid,686000.0,751000.0,35.0,9.0,130.0,67.0,123.0,144.0,91.0,136.0,101.0,128.0,106.0,97.0
90,S Menegola,"Mid,Fwd",719000.0,630000.0,18.4,9.0,115.0,69.0,50.0,120.0,118.0,103.0,88.0,65.0,121.0,71.0
141,S Coniglio,Mid,663000.0,719000.0,31.6,9.0,129.0,146.0,120.0,111.0,121.0,112.0,102.0,92.0,111.0,92.0
155,D Smith,"Fwd,Mid",575000.0,646000.0,29.6,9.0,90.0,91.0,115.0,72.0,91.0,91.0,101.0,94.0,117.0,96.0
189,M Gawn,Ruc,605000.0,785000.0,51.6,9.0,135.0,138.0,78.0,114.0,127.0,143.0,135.0,111.0,111.0,105.0
241,D Martin,Mid,800000.0,601000.0,43.3,9.0,129.0,110.0,127.0,67.0,111.0,73.0,101.0,93.0,48.0,73.0
270,T Mitchell,Mid,896000.0,779000.0,70.0,9.0,123.0,156.0,137.0,148.0,83.0,83.0,147.0,119.0,58.0,149.0
353,J Sicily,"Def,Fwd",523000.0,633000.0,19.0,7.0,93.0,92.0,69.0,NaN,78.0,111.0,NaN,135.0,104.0,71.0
356,A Pearce,Def,197000.0,302000.0,18.6,9.0,51.0,48.0,50.0,51.0,45.0,43.0,50.0,47.0,56.0,29.0
364,Z Merrett,Mid,825000.0,633000.0,26.3,9.0,103.0,23.0,78.0,60.0,121.0,109.0,121.0,64.0,81.0,108.0
381,I Heeney,"Mid,Fwd",649000.0,642000.0,48.7,9.0,97.0,98.0,88.0,97.0,88.0,115.0,91.0,75.0,105.0,105.0
394,T McLean,"Mid,Fwd",603000.0,701000.0,12.8,9.0,98.0,68.0,110.0,103.0,91.0,109.0,87.0,143.0,109.0,101.0
405,J Finlayson,"Def,Mid",170000.0,401000.0,38.8,9.0,75.0,65.0,90.0,59.0,90.0,60.0,65.0,56.0,59.0,46.0
463,S Murray,Def,170000.0,495000.0,61.9,9.0,67.0,76.0,54.0,90.0,85.0,69.0,78.0,101.0,75.0,71.0
484,K Mutch,Mid,170000.0,265000.0,16.7,3.0,10.0,NaN,NaN,NaN,NaN,NaN,71.0,66.0,43.0,NaN
499,I Cumming,Def,170000.0,191000.0,8.1,2.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,22.0
516,E Phillips,Mid,170000.0,242000.0,22.8,2.0,-8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,56.0
526,J Waterman,Fwd,170000.0,375000.0,28.1,9.0,58.0,44.0,54.0,96.0,47.0,49.0,77.0,48.0,67.0,48.0
530,C Rayner,"Fwd,Mid",270000.0,338000.0,31.3,9.0,51.0,35.0,24.0,52.0,85.0,42.0,52.0,63.0,35.0,58.0
541,B Crossley,Ruc,170000.0,235000.0,17.9,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,69.0,44.0,29.0
544,T Kelly,Mid,224000.0,489000.0,46.9,9.0,79.0,81.0,115.0,79.0,63.0,70.0,82.0,92.0,65.0,64.0
550,B Fritsch,Fwd,210000.0,465000.0,29.9,8.0,28.0,74.0,60.0,47.0,47.0,NaN,88.0,91.0,89.0,96.0
555,N Coffield,"Def,Mid",256000.0,368000.0,26.9,7.0,62.0,NaN,NaN,73.0,69.0,79.0,21.0,70.0,61.0,47.0
557,A Naughton,Def,254000.0,342000.0,21.5,8.0,78.0,41.0,61.0,49.0,62.0,53.0,67.0,63.0,3.0,NaN

In [2]:
df.columns

Index(['player', 'position', 'start_price', 'current_price', 'own', 'games',
       'be', 'round_1', 'round_2', 'round_3', 'round_4', 'round_5', 'round_6',
       'round_7', 'round_8'],
      dtype='object')

In [2]:
my_players_df.to_csv("my_players.csv", columns=['player','round_1', 'round_2', 'round_3', 'round_4', 'round_5', 'round_6', 'round_7', 'round_8', 'round_9'], index=False)